apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
data:
  loki-config.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
      log_level: info
    storage_config:
      boltdb:
        directory: /data/loki/index
      filesystem:
        directory: /data/loki/chunks
    schema_config:
      configs:
      - from: 2022-01-01
        store: boltdb
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h
    chunk_store_config:
      max_look_back_period: 0s

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  grafana.ini: |
    [server]
    http_port = 3000
    domain = localhost
    root_url = %(protocol)s://%(domain)s:%(http_port)s/
    [database]
    type = sqlite3
    path = /var/lib/grafana/grafana.db
    [security]
    admin_user = admin
    admin_password = admin
    [auth.anonymous]
    enabled = true
    [auth.basic]
    enabled = false
    [auth.generic_oauth]
    enabled = false
    [auth.ldap]
    enabled = false
    [auth.proxy]
    enabled = false
    [auth.github]
    enabled = false

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: logs
          mountPath: /var/log/grafana
        - name: grafana-config
          mountPath: /etc/grafana/grafana.ini
          subPath: grafana.ini
        - name: loki-config
          mountPath: /etc/loki/loki-config.yaml
          subPath: loki-config.yaml
      volumes:
      - name: logs
        hostPath:
          path: /data/grafana/logs
          type: DirectoryOrCreate
      - name: grafana-config
        configMap:
          name: grafana-config
      - name: loki-config
        configMap:
          name: loki-config
